// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.0
// source: logMessage.proto

package logMessage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequest_TagsKey int32

const (
	LogRequest_APPLICATION LogRequest_TagsKey = 0
	LogRequest_SCOPE       LogRequest_TagsKey = 1
	LogRequest_VERSION     LogRequest_TagsKey = 2
	LogRequest_INSTANCE_ID LogRequest_TagsKey = 3
	LogRequest_HOST        LogRequest_TagsKey = 4
)

// Enum value maps for LogRequest_TagsKey.
var (
	LogRequest_TagsKey_name = map[int32]string{
		0: "APPLICATION",
		1: "SCOPE",
		2: "VERSION",
		3: "INSTANCE_ID",
		4: "HOST",
	}
	LogRequest_TagsKey_value = map[string]int32{
		"APPLICATION": 0,
		"SCOPE":       1,
		"VERSION":     2,
		"INSTANCE_ID": 3,
		"HOST":        4,
	}
)

func (x LogRequest_TagsKey) Enum() *LogRequest_TagsKey {
	p := new(LogRequest_TagsKey)
	*p = x
	return p
}

func (x LogRequest_TagsKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogRequest_TagsKey) Descriptor() protoreflect.EnumDescriptor {
	return file_logMessage_proto_enumTypes[0].Descriptor()
}

func (LogRequest_TagsKey) Type() protoreflect.EnumType {
	return &file_logMessage_proto_enumTypes[0]
}

func (x LogRequest_TagsKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogRequest_TagsKey.Descriptor instead.
func (LogRequest_TagsKey) EnumDescriptor() ([]byte, []int) {
	return file_logMessage_proto_rawDescGZIP(), []int{0, 0}
}

type LogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64              `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LogLine   string             `protobuf:"bytes,2,opt,name=logLine,proto3" json:"logLine,omitempty"`
	Tags      []*LogRequest_Tags `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_logMessage_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogRequest) GetLogLine() string {
	if x != nil {
		return x.LogLine
	}
	return ""
}

func (x *LogRequest) GetTags() []*LogRequest_Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

type LogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_logMessage_proto_rawDescGZIP(), []int{1}
}

func (x *LogResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type LogRequest_Tags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  LogRequest_TagsKey `protobuf:"varint,1,opt,name=type,proto3,enum=protoBuf.LogRequest_TagsKey" json:"type,omitempty"`
	Value string             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LogRequest_Tags) Reset() {
	*x = LogRequest_Tags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logMessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogRequest_Tags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest_Tags) ProtoMessage() {}

func (x *LogRequest_Tags) ProtoReflect() protoreflect.Message {
	mi := &file_logMessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest_Tags.ProtoReflect.Descriptor instead.
func (*LogRequest_Tags) Descriptor() ([]byte, []int) {
	return file_logMessage_proto_rawDescGZIP(), []int{0, 0}
}

func (x *LogRequest_Tags) GetType() LogRequest_TagsKey {
	if x != nil {
		return x.Type
	}
	return LogRequest_APPLICATION
}

func (x *LogRequest_Tags) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_logMessage_proto protoreflect.FileDescriptor

var file_logMessage_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6c, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75, 0x66, 0x22, 0x92, 0x02, 0x0a,
	0x0a, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x67,
	0x4c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x4c,
	0x69, 0x6e, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75, 0x66, 0x2e, 0x4c, 0x6f, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x61, 0x67, 0x73, 0x52, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x1a, 0x4e, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x12, 0x30, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x42, 0x75, 0x66, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54,
	0x61, 0x67, 0x73, 0x4b, 0x65, 0x79, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x4d, 0x0a, 0x07, 0x54, 0x61, 0x67, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x0f, 0x0a,
	0x0b, 0x41, 0x50, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x53, 0x43, 0x4f, 0x50, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x56, 0x45, 0x52,
	0x53, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e,
	0x43, 0x45, 0x5f, 0x49, 0x44, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x4f, 0x53, 0x54, 0x10,
	0x04, 0x22, 0x29, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x44, 0x0a, 0x06,
	0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75, 0x66,
	0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x42, 0x75, 0x66, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x38, 0x0a, 0x1b, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x42, 0x0a, 0x47, 0x72, 0x70, 0x63, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x01, 0x5a,
	0x0b, 0x2f, 0x6c, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_logMessage_proto_rawDescOnce sync.Once
	file_logMessage_proto_rawDescData = file_logMessage_proto_rawDesc
)

func file_logMessage_proto_rawDescGZIP() []byte {
	file_logMessage_proto_rawDescOnce.Do(func() {
		file_logMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_logMessage_proto_rawDescData)
	})
	return file_logMessage_proto_rawDescData
}

var file_logMessage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_logMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_logMessage_proto_goTypes = []interface{}{
	(LogRequest_TagsKey)(0), // 0: protoBuf.LogRequest.TagsKey
	(*LogRequest)(nil),      // 1: protoBuf.LogRequest
	(*LogResponse)(nil),     // 2: protoBuf.LogResponse
	(*LogRequest_Tags)(nil), // 3: protoBuf.LogRequest.Tags
}
var file_logMessage_proto_depIdxs = []int32{
	3, // 0: protoBuf.LogRequest.tags:type_name -> protoBuf.LogRequest.Tags
	0, // 1: protoBuf.LogRequest.Tags.type:type_name -> protoBuf.LogRequest.TagsKey
	1, // 2: protoBuf.Logger.SendMessage:input_type -> protoBuf.LogRequest
	2, // 3: protoBuf.Logger.SendMessage:output_type -> protoBuf.LogResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_logMessage_proto_init() }
func file_logMessage_proto_init() {
	if File_logMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_logMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logMessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogRequest_Tags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_logMessage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logMessage_proto_goTypes,
		DependencyIndexes: file_logMessage_proto_depIdxs,
		EnumInfos:         file_logMessage_proto_enumTypes,
		MessageInfos:      file_logMessage_proto_msgTypes,
	}.Build()
	File_logMessage_proto = out.File
	file_logMessage_proto_rawDesc = nil
	file_logMessage_proto_goTypes = nil
	file_logMessage_proto_depIdxs = nil
}
